name = "niezle-ziolko-workers"
main = "src/index.js"
compatibility_date = "2024-12-10"
compatibility_flags = ["nodejs_compat"]

[dev]
ip = "127.0.0.1"
port = 3000
local_protocol = "http"

routes = [
  { pattern = "*niezleziolko.app/_media/*", zone_name = "niezleziolko.app" },
  { pattern = "*niezleziolko.app/_next/static/media/*", zone_name = "niezleziolko.app" },
  { pattern = "*niezleziolko.app/static.cloudflareinsights.com/", zone_name = "niezleziolko.app" },
  { pattern = "*niezleziolko.app/sibautomation.com/", zone_name = "niezleziolko.app" },
  { pattern = "*niezleziolko.app/api.pushowl.com/", zone_name = "niezleziolko.app" },
  { pattern = "*niezleziolko.app/cdn.pushowl.com/", zone_name = "niezleziolko.app" },
  { pattern = "*niezleziolko.app/in-automate.brevo.com/", zone_name = "niezleziolko.app" },
  { pattern = "*niezleziolko.app/furgonetka.pl/", zone_name = "niezleziolko.app" }
]

[observability]
enabled = true

[limits]
cpu_ms = 3000

[placement]
mode = "smart"