name = "niezle-ziolko-workers"
main = "src/index.js"
compatibility_date = "2024-10-04"
compatibility_flags = ["nodejs_compat"]

workers_dev = false

routes = [
  { pattern = "*niezleziolko.app/static/BalsamiqSans-*", zone_name = "niezleziolko.app" },
  { pattern = "*niezleziolko.app/static/Icons-*", zone_name = "niezleziolko.app" },
  { pattern = "*niezleziolko.app/static/*", zone_name = "niezleziolko.app" },
  { pattern = "*niezleziolko.app/sibautomation.com/", zone_name = "niezleziolko.app" },
  { pattern = "*niezleziolko.app/api.pushowl.com/", zone_name = "niezleziolko.app" },
  { pattern = "*niezleziolko.app/cdn.pushowl.com/", zone_name = "niezleziolko.app" },
  { pattern = "*niezleziolko.app/in-automate.brevo.com/", zone_name = "niezleziolko.app" },
  { pattern = "*niezleziolko.app/furgonetka.pl/", zone_name = "niezleziolko.app" }
]

[observability]
enabled = true

[limits]
cpu_ms = 3000

[placement]
mode = "smart"